### ISSUE TITLE
"  File "data_converter.py", line 10, in <module>     from utils.points_processoint import * ModuleNotFoundError: No module named 'utils.points_processoint'"

### ISSUE THREAD

**Issue by rockywind** [FANG-MING/occupancy-for-nuscenes#2]
Hi,
This error is because the p`oints_processoint` was not found, and the file name was changed to `points_process`.
![image](https://user-images.githubusercontent.com/14838781/220506053-c3daef30-2dc1-494a-8630-25e04c2f94f6.png)

**Comment by FANG-MING** [comment]
> 
thanks for your reminder
