### ISSUE TITLE
 How to save the predicted occupancy file and visualize it？

### ISSUE THREAD

**Issue by rockywind** [FANG-MING/occupancy-for-nuscenes#3]
Hi,

How to reproduce the predicted occupancy demo on the webpage?
I think I should save the predicted occupancy files, but I don't know how to save it?

**Comment by FANG-MING** [comment]
> Hi,
> 
> How to reproduce the predicted occupancy demo on the webpage? I think I should save the predicted occupancy files, but I don't know how to save it?

You can save the prediction results in npy format and use [draw function](https://github.com/FANG-MING/occupancy-for-nuscenes/blob/main/utils/vis_pts.py#L78) for visualization, in that voxel is a three-dimensional tensor, the index indicates its position in three-dimensional space, and the value indicates its predicted label.

**Comment by rockywind** [comment]
Thanks, I have a try!

**Comment by rockywind** [comment]
Hi, @FANG-MING 
I visulized the prediction result, but it looks wrong.
![image](https://user-images.githubusercontent.com/14838781/220720422-6897e1fc-8003-422e-892b-120678de5e2f.png)
This is my draw function.
![image](https://user-images.githubusercontent.com/14838781/220721068-f1a02d76-d1b1-45fa-ab61-230eb32ae98e.png)
This is my save prediction result function.
![image](https://user-images.githubusercontent.com/14838781/220721571-2f52d196-ca0b-478a-8372-00168593ffd7.png)

**Comment by FANG-MING** [comment]
> Hi, @FANG-MING I visulized the prediction result, but it looks wrong. ![image](https://user-images.githubusercontent.com/14838781/220720422-6897e1fc-8003-422e-892b-120678de5e2f.png) This is my draw function. ![image](https://user-images.githubusercontent.com/14838781/220721068-f1a02d76-d1b1-45fa-ab61-230eb32ae98e.png) This is my save prediction result function. ![image](https://user-images.githubusercontent.com/14838781/220721571-2f52d196-ca0b-478a-8372-00168593ffd7.png)

U should convert the label 17 into 0.

**Comment by rockywind** [comment]
Hi, @FANG-MING 
I filtered out the label 17, the result is below.
The visualization result is different from yours.
![image](https://user-images.githubusercontent.com/14838781/220812264-5556a004-3c29-479f-8bb9-da0c1eac175c.png)

This is the code.
![image](https://user-images.githubusercontent.com/14838781/220812535-e003252a-a403-4e9f-8089-f347631dd299.png)

**Comment by FANG-MING** [comment]
> Hi, @FANG-MING I filtered out the label 17, the result is below. The visualization result is different from yours. ![image](https://user-images.githubusercontent.com/14838781/220812264-5556a004-3c29-479f-8bb9-da0c1eac175c.png)
> 
> This is the code. ![image](https://user-images.githubusercontent.com/14838781/220812535-e003252a-a403-4e9f-8089-f347631dd299.png)

You should set the [data_range](https://github.com/FANG-MING/occupancy-for-nuscenes/blob/main/utils/vis_pts.py#L156) to [0, 17].

**Comment by rockywind** [comment]
Hi, 
I set the data range to [0,18], but the result is different from yours.
![image](https://user-images.githubusercontent.com/14838781/220813657-1f9fe077-b34b-4a76-97c7-8317caf940ec.png)
![image](https://user-images.githubusercontent.com/14838781/220813708-a4473bc8-90be-4f56-8af1-225b76898501.png)

**Comment by FANG-MING** [comment]
> Hi, I set the data range to [0,18], but the result is different from yours. ![image](https://user-images.githubusercontent.com/14838781/220813657-1f9fe077-b34b-4a76-97c7-8317caf940ec.png) ![image](https://user-images.githubusercontent.com/14838781/220813708-a4473bc8-90be-4f56-8af1-225b76898501.png)

Convert [classname_to_color](https://github.com/FANG-MING/occupancy-for-nuscenes/blob/main/utils/vis_pts.py#L113) into 
```
classname_to_color = {  # RGB.
        "noise": (0, 0, 0),  
        "movable_object.barrier": (112, 128, 144), 
        "vehicle.bicycle": (220, 20, 60),  
        "vehicle.bus.rigid": (255, 158, 0), 
        "vehicle.car": (255, 158, 0),  
        "vehicle.construction":(255, 158, 0), 
        "vehicle.motorcycle": (255, 158, 0),  
        "human.pedestrian.adult": (0, 0, 230),  
        "movable_object.trafficcone":(112, 128, 144),
        "vehicle.trailer":(255, 158, 0), 
        "vehicle.truck": (255, 158, 0),  
        "flat.driveable_surface": (0, 207, 191),  
        "flat.other":(0, 207, 191),
        "flat.sidewalk": (75, 0, 75),
        "flat.terrain": (0, 207, 191),
        "static.manmade": (222, 184, 135),  
        "static.vegetation": (0, 175, 0),  
    }
```

**Comment by rockywind** [comment]
Hi,
This is the result when I converted the classname_to_color.
It is also different yous.
![image](https://user-images.githubusercontent.com/14838781/220816065-07821e03-8c4f-4cd2-ba62-b204d1f5fe37.png)

**Comment by FANG-MING** [comment]
> Hi, This is the result when I converted the classname_to_color. It is also different yous. ![image](https://user-images.githubusercontent.com/14838781/220816065-07821e03-8c4f-4cd2-ba62-b204d1f5fe37.png)

emmm, Set the [data_range](https://github.com/FANG-MING/occupancy-for-nuscenes/blob/main/utils/vis_pts.py#L156) to [0, 17].

**Comment by rockywind** [comment]
Hi，
There are my results.
Is it correct?
![image](https://user-images.githubusercontent.com/14838781/221075386-363467e9-7ee9-4b57-ab70-c988730ec3be.png)
![image](https://user-images.githubusercontent.com/14838781/221075654-11cea65f-eb49-477d-8ce6-a93794dd6568.png)

**Comment by FANG-MING** [comment]
It looks ok!

**Comment by yebin999** [comment]
Hi @rockywind && @FANG-MING ,
could you help provide your mayavi, pyqt and vtk version? I met some error when I run vis_pts.py caused by mayavi, so I want to check if those three packages version are right.

many thanks!

**Comment by yebin999** [comment]
> Hi @rockywind && @FANG-MING , could you help provide your mayavi, pyqt and vtk version? I met some error when I run vis_pts.py caused by mayavi, so I want to check if those three packages version are right.
> 
> many thanks!

I have solved, ignore this comment.
