### ISSUE TITLE
Is the result of mini-val generated by training on mini-train?

### ISSUE THREAD

**Issue by FrontierBreaker** [FANG-MING/occupancy-for-nuscenes#6]
R.T.

Thanks!

**Comment by FANG-MING** [comment]
It generated by training on train set.

**Comment by FrontierBreaker** [comment]
Got that. Could you tell me how large is the generated occupancy dataset for the whole nuscenes released? and when will it be released? Thanks~

**Comment by FANG-MING** [comment]
> Got that. Could you tell me how large is the generated occupancy dataset for the whole nuscenes released? and when will it be released? Thanks~
We will try to release it as soon as possible. The generated original point cloud data is about 2-3MB per key frame after voxel downsample.

**Comment by FrontierBreaker** [comment]
Got that~ Looking forward to the release : )
